spring:
  application:
    name: user-management







server:
  port: 8081
  servlet:
    context-path: /api

keycloak:
  auth-server-url: http://localhost:8080
  realm: user-management-realm
  resource: user-management-client
  public-client: false
  credentials:
    secret: ohfD0I42WnovBD5YSLTLhUtyuEMrq56t
  admin:
    username: admin
    password: admin
    client-id: admin-cli