spring:
  application:
    name: user-management

  datasource:
    url: jdbc:postgresql://localhost:5432/usermanagement
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: usermanagement_schema

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: user-management-client
            client-secret: ohfD0I42WnovBD5YSLTLhUtyuEMrq56t
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/user-management-realm
            authorization-uri: http://localhost:8080/realms/user-management-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/user-management-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/user-management-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/user-management-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/user-management-realm
          jwk-set-uri: http://localhost:8080/realms/user-management-realm/protocol/openid-connect/certs

server:
  port: 8081
  servlet:
    context-path: /api

keycloak:
  auth-server-url: http://localhost:8080
  realm: user-management-realm
  resource: user-management-client
  public-client: false
  credentials:
    secret: ohfD0I42WnovBD5YSLTLhUtyuEMrq56t
  admin:
    username: admin
    password: admin
    client-id: admin-cli

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  exposed-headers: Authorization
  allow-credentials: true